// =====================================================================
//  Wave analysis test
//  ---------------------------------------------------------------------
//  Exercises the REAL WaveAnalysis code -- this links Source/WaveAnalysis.cpp
//  rather than reimplementing the maths, because a reimplemented test harness
//  only ever proves the harness.
//
//  Signals are generated here at known pitches and known harmonic content, so
//  every assertion below has an answer that was decided before the code ran.
//
//  Build & run:
//      cmake --build build --config Release --target wavetable-test
//      ./build/wavetable_test/Release/wavetable_test.exe
// =====================================================================
#include "../../Source/WaveAnalysis.h"

#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

namespace
{
    int failures = 0;

    void check(bool ok, const std::string& what)
    {
        if (!ok)
        {
            std::printf("  FAIL  %s\n", what.c_str());
            ++failures;
        }
    }

    constexpr double twoPi = 6.283185307179586;

    double cents(double a, double b) { return 1200.0 * std::log2(a / b); }

    // -- Signal generators -----------------------------------------------------
    // Band-limited on purpose: a naive saw generated by sampling a ramp is full
    // of aliases, and testing a pitch detector against aliased input measures the
    // generator instead of the detector.
    std::vector<float> makeTone(double freq, double sampleRate, double seconds,
                                int numHarmonics, bool sawSlopes, double phaseOffset = 0.0)
    {
        const int n = (int)(sampleRate * seconds);
        std::vector<float> out((size_t)n, 0.0f);

        const int maxH = std::min(numHarmonics, (int)((sampleRate * 0.5) / freq) - 1);

        for (int h = 1; h <= maxH; ++h)
        {
            const double amp = sawSlopes ? 1.0 / (double)h : (h == 1 ? 1.0 : 0.0);
            if (amp == 0.0) continue;

            for (int i = 0; i < n; ++i)
                out[(size_t)i] += (float)(amp * std::sin(twoPi * freq * h * (double)i / sampleRate
                                                         + phaseOffset));
        }

        // Normalise, so the silence guard inside detectFundamental never trips for
        // reasons the test did not intend.
        float peak = 0.0f;
        for (float v : out) peak = std::max(peak, std::abs(v));
        if (peak > 0.0f)
            for (float& v : out) v *= 0.9f / peak;

        return out;
    }

    // A tone with its first harmonic removed. Real recordings do this constantly
    // -- a small speaker, a high-passed bass, a telephone -- and a detector that
    // only looks for spectral energy at the fundamental reports an octave high.
    std::vector<float> makeMissingFundamental(double freq, double sampleRate, double seconds)
    {
        const int n = (int)(sampleRate * seconds);
        std::vector<float> out((size_t)n, 0.0f);

        for (int h = 2; h <= 8; ++h)
            for (int i = 0; i < n; ++i)
                out[(size_t)i] += (float)((1.0 / h) * std::sin(twoPi * freq * h * (double)i / sampleRate));

        float peak = 0.0f;
        for (float v : out) peak = std::max(peak, std::abs(v));
        if (peak > 0.0f)
            for (float& v : out) v *= 0.9f / peak;

        return out;
    }

    // Magnitude spectrum of one table, used to prove band limiting.
    std::vector<double> tableSpectrum(const float* table)
    {
        const int n = WaveAnalysis::tableSize;
        std::vector<float> re((size_t)n), im((size_t)n, 0.0f);
        for (int i = 0; i < n; ++i) re[(size_t)i] = table[i];

        WaveAnalysis::fft(re.data(), im.data(), n, false);

        std::vector<double> mag((size_t)(n / 2));
        for (int b = 0; b < n / 2; ++b)
            mag[(size_t)b] = std::sqrt((double)re[(size_t)b] * re[(size_t)b]
                                     + (double)im[(size_t)b] * im[(size_t)b]) * 2.0 / n;
        return mag;
    }
}

int main()
{
    std::printf("Wave analysis tests\n===================\n");

    // -- FFT against a direct transform ----------------------------------------
    // Everything downstream trusts this, so it is checked against the definition
    // rather than against itself.
    std::printf("\nFFT vs direct transform:\n");
    {
        const int n = 64;
        std::vector<float> re((size_t)n), im((size_t)n, 0.0f);
        std::vector<double> refRe((size_t)n, 0.0), refIm((size_t)n, 0.0);

        for (int i = 0; i < n; ++i)
            re[(size_t)i] = (float)std::sin(0.3 * i) + 0.5f * (float)std::cos(1.1 * i);

        for (int k = 0; k < n; ++k)
            for (int i = 0; i < n; ++i)
            {
                const double a = -twoPi * k * i / n;
                refRe[(size_t)k] += re[(size_t)i] * std::cos(a);
                refIm[(size_t)k] += re[(size_t)i] * std::sin(a);
            }

        std::vector<float> copyRe = re;
        WaveAnalysis::fft(re.data(), im.data(), n, false);

        double worst = 0.0;
        for (int k = 0; k < n; ++k)
            worst = std::max(worst, std::max(std::abs(re[(size_t)k] - refRe[(size_t)k]),
                                             std::abs(im[(size_t)k] - refIm[(size_t)k])));
        std::printf("  worst bin deviation: %.3e\n", worst);
        check(worst < 1e-3, "FFT disagrees with the direct transform");

        // Round trip.
        WaveAnalysis::fft(re.data(), im.data(), n, true);
        double worstTrip = 0.0;
        for (int i = 0; i < n; ++i)
            worstTrip = std::max(worstTrip, (double)std::abs(re[(size_t)i] - copyRe[(size_t)i]));
        std::printf("  worst round-trip deviation: %.3e\n", worstTrip);
        check(worstTrip < 1e-4, "FFT round trip did not return the input");

        // A non-power-of-two size must be refused, not half-processed.
        std::vector<float> oddRe(48, 1.0f), oddIm(48, 0.0f);
        WaveAnalysis::fft(oddRe.data(), oddIm.data(), 48, false);
        check(oddRe[0] == 1.0f, "a non-power-of-two size was partly transformed");
    }

    // -- Pitch detection across the keyboard -----------------------------------
    std::printf("\nPitch detection, sawtooth, 48 kHz:\n");
    {
        double worst = 0.0;
        for (int midi = 24; midi <= 96; midi += 6)
        {
            const double freq = 440.0 * std::pow(2.0, (midi - 69) / 12.0);
            const auto tone = makeTone(freq, 48000.0, 0.5, 64, true);
            const auto est = WaveAnalysis::detectFundamental(tone.data(), (int)tone.size(), 48000.0);

            const double err = std::abs(cents(est.frequencyHz, freq));
            worst = std::max(worst, err);

            if (err > 10.0)
                std::printf("  MIDI %3d  wanted %8.2f Hz  got %8.2f Hz  (%.1f cents)\n",
                            midi, freq, est.frequencyHz, err);
            check(err < 10.0, "pitch error above 10 cents at MIDI " + std::to_string(midi));
            check(est.confidence > 0.7, "low confidence on a clean tone at MIDI " + std::to_string(midi));
        }
        std::printf("  worst deviation MIDI 24-96: %.2f cents\n", worst);
    }

    // -- Sample rates other than 48 kHz ----------------------------------------
    std::printf("\nPitch detection at other sample rates:\n");
    for (double sr : { 44100.0, 88200.0, 96000.0 })
    {
        const double freq = 220.0;
        const auto tone = makeTone(freq, sr, 0.5, 64, true);
        const auto est = WaveAnalysis::detectFundamental(tone.data(), (int)tone.size(), sr);
        const double err = std::abs(cents(est.frequencyHz, freq));
        std::printf("  %7.0f Hz: %.2f Hz (%.2f cents)\n", sr, est.frequencyHz, err);
        check(err < 10.0, "pitch error above 10 cents at " + std::to_string((int)sr) + " Hz");
    }

    // -- Pure sine, which has no harmonics for the spectrum to work with -------
    std::printf("\nPitch detection, pure sine:\n");
    {
        const auto tone = makeTone(329.63, 48000.0, 0.5, 1, false);
        const auto est = WaveAnalysis::detectFundamental(tone.data(), (int)tone.size(), 48000.0);
        const double err = std::abs(cents(est.frequencyHz, 329.63));
        std::printf("  E4: %.2f Hz (%.2f cents)\n", est.frequencyHz, err);
        check(err < 10.0, "pure sine pitch error above 10 cents");
    }

    // -- Missing fundamental: the whole reason the spectral pass exists ---------
    std::printf("\nPitch detection, missing fundamental:\n");
    {
        const double freq = 110.0;
        const auto tone = makeMissingFundamental(freq, 48000.0, 0.5);
        const auto est = WaveAnalysis::detectFundamental(tone.data(), (int)tone.size(), 48000.0);
        const double err = std::abs(cents(est.frequencyHz, freq));
        std::printf("  wanted %.2f Hz, got %.2f Hz (%.1f cents)\n", freq, est.frequencyHz, err);
        check(err < 30.0, "octave error on a missing-fundamental tone");
    }

    // -- Signals with no pitch must say so rather than inventing one -----------
    std::printf("\nDegenerate inputs:\n");
    {
        std::vector<float> silence(48000, 0.0f);
        const auto est = WaveAnalysis::detectFundamental(silence.data(), (int)silence.size(), 48000.0);
        check(est.confidence < 0.3, "silence was reported as confidently pitched");
        check(est.frequencyHz > 0.0, "silence produced a non-positive frequency");

        const auto nullArgs = WaveAnalysis::detectFundamental(nullptr, 0, 48000.0);
        check(nullArgs.frequencyHz > 0.0, "null input produced an unusable frequency");

        std::vector<float> tiny(16, 0.5f);
        const auto tinyEst = WaveAnalysis::detectFundamental(tiny.data(), 16, 48000.0);
        check(tinyEst.frequencyHz > 0.0, "a too-short buffer produced an unusable frequency");

        const auto badRate = WaveAnalysis::detectFundamental(tiny.data(), 16, 0.0);
        check(badRate.frequencyHz > 0.0, "a zero sample rate produced an unusable frequency");
        std::printf("  handled\n");
    }

    // -- Harmonic analysis recovers the amplitudes it was given -----------------
    std::printf("\nHarmonic analysis of a 1/h sawtooth:\n");
    {
        const double freq = 200.0;
        const auto tone = makeTone(freq, 48000.0, 0.5, 32, true);
        const auto set = WaveAnalysis::analyseHarmonics(tone.data(), (int)tone.size(), 48000.0, freq);

        check(!set.isEmpty(), "harmonic analysis returned nothing");

        if (!set.isEmpty())
        {
            // Ratios, not absolute levels: the generator normalises its output, so
            // only the shape of the series is known in advance.
            const double first = set.amplitude[0];
            double worst = 0.0;
            for (int h = 2; h <= 8; ++h)
            {
                const double expected = 1.0 / (double)h;
                const double actual = set.amplitude[(size_t)(h - 1)] / first;
                worst = std::max(worst, std::abs(actual - expected) / expected);
            }
            std::printf("  worst amplitude deviation over harmonics 2-8: %.1f%%\n", worst * 100.0);
            check(worst < 0.05, "harmonic amplitudes deviate more than 5% from 1/h");

            // Everything above the generated limit must be near zero, or the
            // analysis is reading leakage as signal.
            double aboveLimit = 0.0;
            for (int h = 40; h <= std::min(80, set.size()); ++h)
                aboveLimit = std::max(aboveLimit, (double)set.amplitude[(size_t)(h - 1)] / first);
            std::printf("  strongest harmonic above the source limit: %.4f of the first\n", aboveLimit);
            check(aboveLimit < 0.02, "harmonic analysis invented content above the source bandwidth");
        }
    }

    // -- Phase is kept, not discarded ------------------------------------------
    // Throwing phase away rebuilds every waveform as a pile of cosines, which
    // sounds hollow and looks nothing like the source. Two harmonics are built a
    // known quarter cycle apart, and the analysis has to report that gap.
    std::printf("\nPhase is preserved:\n");
    {
        const double freq = 200.0;
        const double sr = 48000.0;
        const int n = (int)(sr * 0.5);

        std::vector<float> sig((size_t)n, 0.0f);
        for (int i = 0; i < n; ++i)
        {
            const double t = twoPi * freq * (double)i / sr;
            sig[(size_t)i] = (float)(0.6 * std::cos(t)              // first harmonic, no offset
                                   + 0.3 * std::cos(2.0 * t - 1.5707963));  // second, a quarter cycle late
        }

        const auto set = WaveAnalysis::analyseHarmonics(sig.data(), n, sr, freq);
        check(set.size() >= 2, "phase test produced fewer than two harmonics");

        if (set.size() >= 2)
        {
            // Not the raw difference. The analysis reads from the body of the
            // signal, not from sample zero, and a time offset of theta shifts
            // harmonic h by h*theta -- so the raw gap depends on where it looked.
            // (phase2 - 2*phase1) cancels that shift exactly, and it is the
            // quantity that decides the shape of the wave.
            double relative = (double)set.phase[1] - 2.0 * (double)set.phase[0];
            while (relative < -3.14159265) relative += twoPi;
            while (relative >  3.14159265) relative -= twoPi;

            std::printf("  shift-invariant phase of harmonic 2: %.4f rad (wanted %.4f)\n",
                        relative, -1.5707963);
            check(std::abs(relative + 1.5707963) < 0.05, "the phase relationship was not preserved");

            const double ratio = set.amplitude[1] / set.amplitude[0];
            std::printf("  amplitude ratio: %.4f (wanted 0.5)\n", ratio);
            check(std::abs(ratio - 0.5) < 0.02, "harmonic amplitudes were not measured correctly");
        }
    }

    // -- The rendered table must actually be one period ------------------------
    // A table whose two ends do not meet clicks once per cycle. This is the whole
    // reason the cycle is built from harmonics rather than cut out of the file.
    std::printf("\nRendered table is periodic:\n");
    {
        const double freq = 200.0;
        const auto tone = makeTone(freq, 48000.0, 0.5, 32, true);
        const auto set = WaveAnalysis::analyseHarmonics(tone.data(), (int)tone.size(), 48000.0, freq);

        std::vector<float> table((size_t)WaveAnalysis::tableSize);
        WaveAnalysis::renderTable(set, 64, table.data());

        const int n = WaveAnalysis::tableSize;

        // Compare the step across the wrap against the biggest step anywhere else.
        // If the wrap is a discontinuity it stands out by orders of magnitude.
        double worstInternal = 0.0;
        for (int i = 1; i < n; ++i)
            worstInternal = std::max(worstInternal, std::abs((double)table[(size_t)i] - table[(size_t)i - 1]));

        const double wrapStep = std::abs((double)table[0] - table[(size_t)n - 1]);
        std::printf("  step across the wrap: %.5f   worst step elsewhere: %.5f\n", wrapStep, worstInternal);
        check(wrapStep <= worstInternal * 1.5, "the table does not join up at the wrap");

        // And it must be normalised, or one waveform is louder than the next.
        double peak = 0.0;
        for (float v : table) peak = std::max(peak, (double)std::abs(v));
        check(peak > 0.1, "rendered table is silent");
    }

    // -- A stored table must rebuild the harmonics it came from ----------------
    // A saved waveform keeps one table, not the whole ladder, and the other ten
    // levels are rebuilt from it on load. That only works if the round trip is
    // lossless, so it is checked rather than assumed.
    std::printf("\nTable to harmonics round trip:\n");
    {
        const double freq = 200.0;
        const auto tone = makeTone(freq, 48000.0, 0.5, 40, true);
        const auto original = WaveAnalysis::analyseHarmonics(tone.data(), (int)tone.size(), 48000.0, freq);

        std::vector<float> table((size_t)WaveAnalysis::tableSize);
        WaveAnalysis::renderTable(original, 40, table.data());

        const auto recovered = WaveAnalysis::harmonicsFromTable(table.data());
        check(recovered.size() >= 40, "recovered too few harmonics from a table");

        // Compared against the table's own content, not the source: renderTable
        // normalises, so only the shape survives, and the shape is the point.
        double worstAmp = 0.0, worstPhase = 0.0;
        const double scale = recovered.amplitude[0] / std::max(1e-9f, original.amplitude[0]);

        for (int h = 1; h <= 40; ++h)
        {
            const double wanted = original.amplitude[(size_t)(h - 1)] * scale;
            worstAmp = std::max(worstAmp, std::abs(recovered.amplitude[(size_t)(h - 1)] - wanted));

            double dp = (double)recovered.phase[(size_t)(h - 1)] - (double)original.phase[(size_t)(h - 1)];
            while (dp < -3.14159265) dp += twoPi;
            while (dp >  3.14159265) dp -= twoPi;
            if (wanted > 1e-4)
                worstPhase = std::max(worstPhase, std::abs(dp));
        }

        std::printf("  worst amplitude difference: %.2e   worst phase difference: %.2e rad\n",
                    worstAmp, worstPhase);
        check(worstAmp < 1e-5, "amplitudes did not survive the table round trip");
        check(worstPhase < 1e-3, "phases did not survive the table round trip");

        // And rebuilding the ladder from the recovered set must match rebuilding
        // it from the original.
        std::vector<float> rebuilt((size_t)WaveAnalysis::tableSize);
        WaveAnalysis::renderTable(recovered, 40, rebuilt.data());

        double worstSample = 0.0;
        for (int i = 0; i < WaveAnalysis::tableSize; ++i)
            worstSample = std::max(worstSample, (double)std::abs(rebuilt[(size_t)i] - table[(size_t)i]));
        std::printf("  worst sample difference after rebuild: %.2e\n", worstSample);
        check(worstSample < 1e-5, "a table rebuilt from its own harmonics differs from the original");
    }

    // -- Band limiting: each level must be empty above its own harmonic limit ---
    std::printf("\nMipmap band limiting:\n");
    {
        const double freq = 200.0;
        const auto tone = makeTone(freq, 48000.0, 0.5, 200, true);
        const auto set = WaveAnalysis::analyseHarmonics(tone.data(), (int)tone.size(), 48000.0, freq);

        std::vector<float> mips((size_t)(WaveAnalysis::mipLevels * WaveAnalysis::tableSize));
        WaveAnalysis::renderMipmaps(set, mips.data());

        for (int level = 0; level < WaveAnalysis::mipLevels; ++level)
        {
            const float* table = mips.data() + (size_t)level * WaveAnalysis::tableSize;
            const auto mag = tableSpectrum(table);

            const int limit = WaveAnalysis::harmonicsAtLevel(level);
            double aboveLimit = 0.0;
            for (int b = limit + 2; b < (int)mag.size(); ++b)
                aboveLimit = std::max(aboveLimit, mag[(size_t)b]);

            check(aboveLimit < 1e-4, "level " + std::to_string(level) + " has content above its limit");
            if (level <= 6)
                std::printf("  level %2d  limit %4d harmonics  strongest above it: %.2e\n",
                            level, limit, aboveLimit);
        }

        // Level 0 sets the gain for the ladder, and every level shares it.
        double peak0 = 0.0;
        for (int i = 0; i < WaveAnalysis::tableSize; ++i)
            peak0 = std::max(peak0, (double)std::abs(mips[(size_t)i]));
        std::printf("  level 0 peak: %.4f\n", peak0);
        check(std::abs(peak0 - 1.0) < 1e-3, "level 0 is not normalised to unity peak");

        // Quieter as harmonics come off, never louder. A level that overshoots
        // means the shared gain was not shared.
        for (int level = 1; level < WaveAnalysis::mipLevels; ++level)
        {
            double peak = 0.0;
            const float* table = mips.data() + (size_t)level * WaveAnalysis::tableSize;
            for (int i = 0; i < WaveAnalysis::tableSize; ++i)
                peak = std::max(peak, (double)std::abs(table[i]));
            check(peak <= 1.05, "level " + std::to_string(level) + " is louder than level 0");
        }
    }

    // -- Level choice must keep the top harmonic below Nyquist -----------------
    std::printf("\nLevel choice:\n");
    for (double sr : { 44100.0, 48000.0, 96000.0 })
    {
        bool allSafe = true;
        int lastLevel = -1;
        bool monotonic = true;

        for (int midi = 0; midi <= 127; ++midi)
        {
            const double freq = 440.0 * std::pow(2.0, (midi - 69) / 12.0);
            const int level = WaveAnalysis::levelForFrequency(freq, sr);
            const double topHarmonic = (double)WaveAnalysis::harmonicsAtLevel(level) * freq;

            // The single-harmonic level cannot band-limit any further, so a note
            // above Nyquist itself is out of scope -- nothing can help that.
            if (level < WaveAnalysis::mipLevels - 1 && topHarmonic >= sr * 0.5)
                allSafe = false;

            if (level < lastLevel) monotonic = false;
            lastLevel = level;
        }

        std::printf("  %7.0f Hz: band limited across MIDI 0-127: %s\n", sr, allSafe ? "yes" : "NO");
        check(allSafe, "a level let a harmonic past Nyquist at " + std::to_string((int)sr) + " Hz");
        check(monotonic, "level choice is not monotonic in frequency at " + std::to_string((int)sr) + " Hz");
    }
    check(WaveAnalysis::levelForFrequency(0.0, 48000.0) == 0, "a zero frequency did not fall back to level 0");
    check(WaveAnalysis::levelForFrequency(440.0, 0.0) == 0, "a zero sample rate did not fall back to level 0");

    // -- Full Sample playback lands the recorded pitch on the played note -------
    // The headline claim of the feature: drop in a sample recorded at any pitch,
    // and the note you press is the note you hear. Rather than assert the formula
    // algebraically, this drives a phase accumulator exactly the way SynthVoice
    // does, renders the result, and measures what pitch actually came out.
    std::printf("\nFull Sample playback tuning:\n");
    {
        const double hostRate = 48000.0;

        // A file recorded at F#3, at a rate that is not the host's -- so a wrong
        // formula that happens to ignore the file's rate cannot pass by luck.
        const double fileRate = 44100.0;
        const double rootHz = 185.0;

        const int fileLength = (int)(fileRate * 1.0);
        std::vector<float> file((size_t)fileLength);
        for (int i = 0; i < fileLength; ++i)
            file[(size_t)i] = (float)(0.9 * std::sin(twoPi * rootHz * (double)i / fileRate));

        // The same reserve the importer leaves at both ends for the loop crossfade
        // and the interpolator.
        const int crossfade = (int)(0.010 * fileRate);
        const int loopStart = crossfade + 3;
        const int loopLength = fileLength - loopStart - 3;

        const double scale = WaveAnalysis::playbackPhaseScale(fileRate, rootHz, loopLength);

        for (double note : { WaveAnalysis::middleCHz, 440.0, 110.0 })
        {
            // Exactly what SynthVoice does: the ordinary phase increment for this
            // note, multiplied by the slot's scale.
            const double delta = twoPi * note / hostRate * scale;

            const int outputLength = (int)(hostRate * 0.5);
            std::vector<float> output((size_t)outputLength);

            double angle = 0.0;
            for (int i = 0; i < outputLength; ++i)
            {
                const double phase01 = angle / twoPi;
                const double position = (double)loopStart + phase01 * (double)loopLength;

                const int index = (int)position;
                const float frac = (float)(position - (double)index);
                output[(size_t)i] = file[(size_t)index]
                                  + frac * (file[(size_t)index + 1] - file[(size_t)index]);

                angle += delta;
                if (angle >= twoPi) angle -= twoPi;
            }

            const auto est = WaveAnalysis::detectFundamental(output.data(), outputLength, hostRate);
            const double err = std::abs(cents(est.frequencyHz, note));

            char wanted[32], got[32];
            WaveAnalysis::describePitch(note, wanted, sizeof(wanted));
            WaveAnalysis::describePitch(est.frequencyHz, got, sizeof(got));

            std::printf("  played %-9s -> heard %-9s (%.2f cents off)\n", wanted, got, err);
            check(err < 15.0, "a sample recorded at 185 Hz did not play in tune");
        }

        // And when no pitch could be found, middle C must play the file at its
        // recorded speed instead of transposing it for no reason the user can see.
        const double unpitchedScale = WaveAnalysis::playbackPhaseScale(fileRate, WaveAnalysis::middleCHz,
                                                                       loopLength);
        const double deltaAtC = twoPi * WaveAnalysis::middleCHz / hostRate * unpitchedScale;
        const double filePerOutput = deltaAtC / twoPi * (double)loopLength;
        const double wantedRatio = fileRate / hostRate;

        std::printf("  unpitched: %.6f file samples per output sample (wanted %.6f)\n",
                    filePerOutput, wantedRatio);
        check(std::abs(filePerOutput - wantedRatio) < 1e-9,
              "an unpitched sample was not played at its recorded speed on middle C");

        check(WaveAnalysis::playbackPhaseScale(0.0, 185.0, 100) == 1.0, "a zero file rate did not fall back to 1");
        check(WaveAnalysis::playbackPhaseScale(44100.0, 0.0, 100) == 1.0, "a zero root pitch did not fall back to 1");
        check(WaveAnalysis::playbackPhaseScale(44100.0, 185.0, 0) == 1.0, "a zero loop length did not fall back to 1");
    }

    // -- Pitch naming ----------------------------------------------------------
    std::printf("\nPitch naming:\n");
    {
        char name[32];

        WaveAnalysis::describePitch(440.0, name, sizeof(name));
        std::printf("  440.00 Hz -> %s\n", name);
        check(std::string(name).rfind("A4", 0) == 0, "440 Hz was not named A4");

        WaveAnalysis::describePitch(WaveAnalysis::middleCHz, name, sizeof(name));
        std::printf("  261.63 Hz -> %s\n", name);
        check(std::string(name).rfind("C4", 0) == 0, "middle C was not named C4");

        WaveAnalysis::describePitch(0.0, name, sizeof(name));
        check(name[0] == '\0', "a non-positive frequency produced a note name");

        check(std::abs(WaveAnalysis::semitonesFromMiddleC(WaveAnalysis::middleCHz * 2.0) - 12.0) < 1e-9,
              "an octave above middle C is not 12 semitones");
        check(WaveAnalysis::semitonesFromMiddleC(0.0) == 0.0, "a non-positive frequency returned a interval");
    }

    std::printf("\n%s (%d failure%s)\n", failures == 0 ? "ALL PASSED" : "FAILED",
                failures, failures == 1 ? "" : "s");
    return failures == 0 ? 0 : 1;
}
